### ISSUE TITLE
Google maps includes domain filter

### ISSUE THREAD

**Issue by KMCGamer** [kylecarhart/Google-Domain-Filter#36]
Don't run scripts when on Google Maps.

<div align="center">
<img src="https://user-images.githubusercontent.com/6385983/103023391-df6f9f00-451b-11eb-8f8e-78bb60ae6264.gif" width="600px"/>
</div>

**Comment by kylecarhart** [comment]
Fixed in 11936c7b6e996f94f7600e87ba4657c570cd9c41
