### ISSUE TITLE
Pressing the back button doesnt filter or highlight domains

### ISSUE THREAD

**Issue by KMCGamer** [kylecarhart/Google-Domain-Filter#39]
![Screen Recording 2021-01-05 at 7 49 16 PM](https://user-images.githubusercontent.com/6385983/103716231-89c1da80-4f90-11eb-943c-4400c263203f.gif)

**Comment by kylecarhart** [comment]
This only happens for the default filter mode

**Comment by kylecarhart** [comment]
Maybe something about this? https://stackoverflow.com/questions/36187908/chrome-tabs-onupdated-addlistener-doesnt-work-on-cached-pages
